name: Data Preprocessing Automation

on:
  push:
    branches:
      - main
    paths:
      - "namadataset_raw/**"
      - "preprocessing/automate_naumi.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run preprocessing script
        run: |
          cd preprocessing
          python automate_naumi.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add namadataset_preprocessing/data_bersih.csv
          git commit -m "Auto-update dataset via CI" || echo "No changes to commit"
          git push
